/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import sql.Conexion;

/**
 *
 * @author Concepción
 */
public class Mostrar_redes extends javax.swing.JFrame {

    private static Mostrar_redes t = null;

    public static Mostrar_redes getMostrar_redes() {
        if (t == null) {
            t = new Mostrar_redes();
        }
        return t;
    }

    /**
     * Creates new form Mostrar_redes
     */
    public Mostrar_redes() {
        initComponents();
        String cabecera[] = {"Cód.", "Rut", "Nombre", "Apellido", "Cel", "Email", "Sueldo", "E_Civil", "Depto"};
        String datos[][] = {};
        DefaultTableModel model;
        model = new DefaultTableModel(datos, cabecera);
        jbredes.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jbredes = new javax.swing.JTable();
        btnmostrar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbredes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jbredes);

        btnmostrar2.setText("Mostrar");
        btnmostrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmostrar2MouseClicked(evt);
            }
        });
        btnmostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrar2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("EMPLEADOS DEPTO REDES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnmostrar2)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnmostrar2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmostrar2ActionPerformed

    private void btnmostrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmostrar2MouseClicked
        String cabecera[] = {"Cód.", "Rut", "Nombre", "Apellido", "Cel", "Email", "Sueldo", "E_Civil", "Depto"};
        String datos[][] = {};
        DefaultTableModel model;
        model = new DefaultTableModel(datos, cabecera);
        jbredes.setModel(model);
        //crea el método
        try {
            //mostrar datos
            Connection conexion = Conexion.getConexion();
            Statement smt = conexion.createStatement();
            String query = "SELECT * FROM empleados";
            ResultSet rs = smt.executeQuery(query);

            /*DefaultTableModel model = (DefaultTableModel) tbsemilla.getModel();*/ //representa el formato de la tabla no la tabla en si 
            while (rs.next()) {
                //sacamos datos de grilla
                int cod = rs.getInt("codigo");
                String rut = rs.getString("rut");
                String nom = rs.getString("nombre");
                String apellido = rs.getString("apellido");
                int cel = rs.getInt("celular");
                String mail = rs.getString("email");
                int sueldo = rs.getInt("sueldo_bruto");
                String e_civil = rs.getString("est_civil");
                String depto = rs.getString("nom_dept");
                //condicion que selecciona solo pelicula de categoria romance
                if (depto.equals("Redes")) {
                    Object[] fila = new Object[]{cod, rut, nom, apellido, cel, mail, sueldo, e_civil, depto};
                    model.addRow(fila);
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnmostrar2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar_redes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar_redes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar_redes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar_redes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar_redes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmostrar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jbredes;
    // End of variables declaration//GEN-END:variables
}
