/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multinacional;

import javax.swing.JOptionPane;

/**
 *
 * @author Xberto
 */
public class Ingresar extends javax.swing.JFrame {

    private static Ingresar t = null;
    
    public static Ingresar getIngresar(){
        if(t==null)
            t = new Ingresar();
        return t;
    }
    
    /**
     * Creates new form Ingresar
     */
    private Ingresar() {
        initComponents();
        txtmarca.setEnabled(false);
        cbxcarga.setEnabled(false);
        txtpies.setEnabled(false);
        cbxtipo.setEnabled(false);
        rbtnhombre.setEnabled(false);
        rbtnmujer.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cbxproducto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxcarga = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtpies = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxtipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        rbtnmujer = new javax.swing.JRadioButton();
        rbtnhombre = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Producto");
        setResizable(false);

        jLabel1.setText("Productos");

        cbxproducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lavadora", "Pantalón", "Refrigerador" }));
        cbxproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxproductoActionPerformed(evt);
            }
        });

        jLabel2.setText("Código");

        jLabel3.setText("Precio");

        jLabel4.setText("Stock");

        txtcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodeKeyReleased(evt);
            }
        });

        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprecioKeyReleased(evt);
            }
        });

        txtstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstockKeyReleased(evt);
            }
        });

        jLabel5.setText("Marca");

        jLabel6.setText("Carga");

        cbxcarga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Por Arriba", "Por Costado" }));
        cbxcarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcargaActionPerformed(evt);
            }
        });

        jLabel7.setText("Pies");

        txtpies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpiesKeyReleased(evt);
            }
        });

        jLabel8.setText("Tipo");

        cbxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Jeans", "Cotelé", "Tela" }));

        jLabel9.setText("Sexo");

        buttonGroup1.add(rbtnmujer);
        rbtnmujer.setText("Mujer");

        buttonGroup1.add(rbtnhombre);
        rbtnhombre.setText("Hombre");

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcode)
                            .addComponent(txtprecio)
                            .addComponent(txtstock)
                            .addComponent(cbxcarga, 0, 110, Short.MAX_VALUE)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cbxproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnhombre)
                                .addGap(10, 10, 10)
                                .addComponent(rbtnmujer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbxproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(rbtnhombre)
                            .addComponent(rbtnmujer))
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxcarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxcargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxcargaActionPerformed

    private void cbxproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxproductoActionPerformed
        String producto = cbxproducto.getSelectedItem().toString();
        if(producto.equals("Refrigerador")){
            txtmarca.setEnabled(true);
            cbxcarga.setEnabled(false);
            txtpies.setEnabled(true);
            cbxtipo.setEnabled(false);
            rbtnhombre.setEnabled(false);
            rbtnmujer.setEnabled(false);
        }
        if(producto.equals("Lavadora")){
            txtmarca.setEnabled(true);
            cbxcarga.setEnabled(true);
            txtpies.setEnabled(false);
            cbxtipo.setEnabled(false);
            rbtnhombre.setEnabled(false);
            rbtnmujer.setEnabled(false);
        }
        if(producto.equals("Pantalón")){
            txtmarca.setEnabled(false);
            cbxcarga.setEnabled(false);
            txtpies.setEnabled(false);
            cbxtipo.setEnabled(true);
            rbtnhombre.setEnabled(true);
            rbtnmujer.setEnabled(true);
        }
    }//GEN-LAST:event_cbxproductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verifica(javax.swing.JTextField t){
        String teclado = t.getText();
        if(teclado.length()>0){
            char tecla = teclado.charAt(teclado.length()-1);
            teclado = teclado.substring(0,teclado.length()-1);
            if(!Character.isDigit(tecla))
                t.setText(teclado);
        }

    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String producto = cbxproducto.getSelectedItem().toString();
        RegistroProducto pr = RegistroProducto.getInstancia();
        if(txtcode.getText().isEmpty() || txtprecio.getText().isEmpty() || 
                    txtstock.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Faltan Datos por Ingresar");
            return;
        }
        if(producto.equals("Pantalón")){
            if(cbxtipo.getSelectedItem().toString().equals("Seleccione")
                 || (!rbtnhombre.isSelected() && !rbtnmujer.isSelected())){
                JOptionPane.showMessageDialog(this,"Faltan Datos por Ingresar");
                return;
            }
            char sexo;
            /*if(rbtnhombre.isSelected())
                sexo = 'H';
            else
                sexo = 'M';
            */
            if(rbtnmujer.isSelected())
                sexo='M';
            else
                sexo='H';
            Pantalon p = new Pantalon(
                    cbxtipo.getSelectedItem().toString(),
                    sexo,
                    Integer.parseInt(txtcode.getText()),
                    Integer.parseInt(txtprecio.getText()),
                    Integer.parseInt(txtstock.getText())
            );
            if(pr.agregar(p))
                JOptionPane.showMessageDialog(this,"Pantalón Ingresado A La Perfecçao");
            else
                JOptionPane.showMessageDialog(this,"Producto Ya Existe");
        }
        if(producto.equals("Refrigerador")){
            if(txtmarca.getText().isEmpty() || txtpies.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Faltan Datos por Ingresar");
                return;
            }
            Refrigerador r = new Refrigerador(
                    Integer.parseInt(txtpies.getText()),
                    txtmarca.getText(),
                    Integer.parseInt(txtcode.getText()),
                    Integer.parseInt(txtprecio.getText()),
                    Integer.parseInt(txtstock.getText())                    
            );
            if(pr.agregar(r))
                JOptionPane.showMessageDialog(this,"Refrigerador Ingresado a la Perfeçcao");
            else
                JOptionPane.showMessageDialog(this,"Producto Ya Existe");
        }
        if(producto.equals("Lavadora")){
            if(txtmarca.getText().isEmpty() || cbxcarga.getSelectedItem().toString().equals("Seleccione")){
                JOptionPane.showMessageDialog(this,"Faltan Datos por Ingresar");
                return;
            }
            Lavadora l = new Lavadora(
                    cbxcarga.getSelectedItem().toString(),
                    txtmarca.getText(),
                    Integer.parseInt(txtcode.getText()),
                    Integer.parseInt(txtprecio.getText()),
                    Integer.parseInt(txtstock.getText())      
            );
            if(pr.agregar(l))
                JOptionPane.showMessageDialog(this,"Lavadora Ingresada a la Perfeçcao");
            else
                JOptionPane.showMessageDialog(this,"Producto Ya Existe");
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void txtcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodeKeyReleased
        verifica(txtcode);
    }//GEN-LAST:event_txtcodeKeyReleased

    private void txtprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyReleased
        verifica(txtprecio);
    }//GEN-LAST:event_txtprecioKeyReleased

    private void txtstockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstockKeyReleased
        verifica(txtstock);
    }//GEN-LAST:event_txtstockKeyReleased

    private void txtpiesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpiesKeyReleased
        verifica(txtpies);
    }//GEN-LAST:event_txtpiesKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxcarga;
    private javax.swing.JComboBox<String> cbxproducto;
    private javax.swing.JComboBox<String> cbxtipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtnhombre;
    private javax.swing.JRadioButton rbtnmujer;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtpies;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
