/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author daniela
 */
public class Controles extends javax.swing.JFrame {

    /**
     * Creates new form Controles
     */
    public Controles() {
        initComponents();
        grupogenero.add(rbnhombre);
        grupogenero.add(rbnmujer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupogenero = new javax.swing.ButtonGroup();
        rbnhombre = new javax.swing.JRadioButton();
        rbnmujer = new javax.swing.JRadioButton();
        cbxble = new javax.swing.JCheckBox();
        cbxgimnacio = new javax.swing.JCheckBox();
        cbxmusica = new javax.swing.JCheckBox();
        jspnum = new javax.swing.JSpinner();
        btnprueba = new javax.swing.JButton();
        btnmensaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbnhombre.setText("Hombre");

        rbnmujer.setText("Mujer");

        cbxble.setText("Baile");

        cbxgimnacio.setText("Gimnacio");

        cbxmusica.setText("Musica");

        btnprueba.setText("Prueba");
        btnprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpruebaActionPerformed(evt);
            }
        });

        btnmensaje.setText("Mensaje");
        btnmensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxgimnacio)
                    .addComponent(rbnhombre)
                    .addComponent(rbnmujer)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxble)
                                .addGap(154, 154, 154)
                                .addComponent(jspnum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxmusica))
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnprueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(rbnhombre)
                .addGap(18, 18, 18)
                .addComponent(rbnmujer)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxble)
                    .addComponent(jspnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprueba, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxgimnacio)
                        .addGap(18, 18, 18)
                        .addComponent(cbxmusica))
                    .addComponent(btnmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpruebaActionPerformed
      //simular un dato de mysql consulta
      String genero = "H";
      if("M".equals(genero)){
          rbnmujer.setSelected(true);   
      }
      if("H".equals(genero)){
          rbnhombre.setSelected(true);
          
      }
        if (rbnhombre.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Hombre");
            
        }else if (rbnmujer.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Mujer");
        }else {
            JOptionPane.showMessageDialog(null, "No selecciono Genero");
        }
        if(cbxble.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Baile");
        }
        if(cbxgimnacio.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Gimnacio");
        }
        if(cbxmusica.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Musica");
        }
        
        
            JOptionPane.showMessageDialog(null,jspnum.getValue());
        
    }//GEN-LAST:event_btnpruebaActionPerformed

    private void btnmensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmensajeActionPerformed
    //agregar icono personalizado, falta dimencionarlo para la ventana de mensaje
        ImageIcon icono = new ImageIcon("src/img/search.jpg");
         //JOptionPane.showMessageDialog(null,"Hola Daniela");null posicion cero de la pantalla, mas mensaje o variable
         //JOptionPane.showMessageDialog(this,"Hola Daniela");this posicion centralizada en la pantalla
         //personalizar ventana, Agrega el titulo a la ventana y modifica el icono por :advertencia, pregunta, otros
         //JOptionPane.showMessageDialog(this,"Hola Daniela","Mi Ventana de Prueba",JOptionPane.QUESTION_MESSAGE );
         
//ingresar datos en el mensaje
         //String respuesta =JOptionPane.showInputDialog(this,"Hola Daniela","Mi Ventana de Prueba",JOptionPane.QUESTION_MESSAGE);
         JOptionPane.showMessageDialog(this,"Hola Daniela","Mi Ventana de Prueba",JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_btnmensajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmensaje;
    private javax.swing.JButton btnprueba;
    private javax.swing.JCheckBox cbxble;
    private javax.swing.JCheckBox cbxgimnacio;
    private javax.swing.JCheckBox cbxmusica;
    private javax.swing.ButtonGroup grupogenero;
    private javax.swing.JSpinner jspnum;
    private javax.swing.JRadioButton rbnhombre;
    private javax.swing.JRadioButton rbnmujer;
    // End of variables declaration//GEN-END:variables
}
