
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Xberto
 */
public class Marco extends javax.swing.JFrame {

    /**
     * Creates new form Marco
     */
    public Marco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnC = new javax.swing.JButton();
        txtClp = new javax.swing.JTextField();
        txteu = new javax.swing.JTextField();
        txtusd = new javax.swing.JTextField();
        txtyen = new javax.swing.JTextField();
        txtreal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Peso Chileno");

        jLabel2.setText("Euro");

        jLabel3.setText("Dolar");

        jLabel4.setText("Yen");

        jLabel5.setText("Real");

        btnC.setText("Convertir");
        btnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCMouseClicked(evt);
            }
        });

        txtClp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtClpMouseClicked(evt);
            }
        });
        txtClp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClpKeyReleased(evt);
            }
        });

        txteu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txteuMouseClicked(evt);
            }
        });
        txteu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txteuKeyReleased(evt);
            }
        });

        txtusd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusdMouseClicked(evt);
            }
        });
        txtusd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusdKeyReleased(evt);
            }
        });

        txtyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtyenMouseClicked(evt);
            }
        });
        txtyen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtyenKeyReleased(evt);
            }
        });

        txtreal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtrealMouseClicked(evt);
            }
        });
        txtreal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrealKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtClp)
                            .addComponent(txteu)
                            .addComponent(txtusd)
                            .addComponent(txtyen)
                            .addComponent(txtreal, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnC)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txteu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtusd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtreal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnC)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClpMouseClicked
        limpiaInput();
    }//GEN-LAST:event_txtClpMouseClicked

    private void txteuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txteuMouseClicked
        limpiaInput();
    }//GEN-LAST:event_txteuMouseClicked

    private void txtusdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusdMouseClicked
        limpiaInput();
    }//GEN-LAST:event_txtusdMouseClicked

    private void txtyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtyenMouseClicked
        limpiaInput();
    }//GEN-LAST:event_txtyenMouseClicked

    private void txtrealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrealMouseClicked
        limpiaInput();
    }//GEN-LAST:event_txtrealMouseClicked

    private void btnCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseClicked
        int numero;
        if(!txtClp.getText().isEmpty()){
            numero = Integer.parseInt(txtClp.getText());
            txtusd.setText(""+(numero*0.00155));
            txtusd.setCaretPosition(0);
            txteu.setText(""+numero*0.00130287136);
            txteu.setCaretPosition(0);
            txtyen.setText(""+numero*0.174353206);
            txtyen.setCaretPosition(0);
            txtreal.setText(""+numero*0.00506502843);
            txtreal.setCaretPosition(0);
        }
    }//GEN-LAST:event_btnCMouseClicked

    private void verifica(javax.swing.JTextField t, char tecla){
        String teclado = t.getText();
        teclado = teclado.substring(0,teclado.length()-1);
        if(!Character.isDigit(tecla))
            t.setText(teclado);
    }
    
    
    private void txtClpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClpKeyReleased
        verifica(txtClp,evt.getKeyChar());
    }//GEN-LAST:event_txtClpKeyReleased

    private void txteuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteuKeyReleased
        verifica(txteu,evt.getKeyChar());
    }//GEN-LAST:event_txteuKeyReleased

    private void txtusdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusdKeyReleased
       verifica(txtusd,evt.getKeyChar());
    }//GEN-LAST:event_txtusdKeyReleased

    private void txtyenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyenKeyReleased
        verifica(txtyen,evt.getKeyChar());
    }//GEN-LAST:event_txtyenKeyReleased

    private void txtrealKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrealKeyReleased
        verifica(txtreal,evt.getKeyChar());
    }//GEN-LAST:event_txtrealKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marco().setVisible(true);
            }
        });
    }

    private void limpiaInput(){
        txtClp.setText("");
        txtusd.setText("");
        txtreal.setText("");
        txtyen.setText("");
        txteu.setText("");
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtClp;
    private javax.swing.JTextField txteu;
    private javax.swing.JTextField txtreal;
    private javax.swing.JTextField txtusd;
    private javax.swing.JTextField txtyen;
    // End of variables declaration//GEN-END:variables
}
