CREATE TABLE `empresa`.`empleados` (
  `CODIGO` INT(3) NOT NULL,
  `RUT` VARCHAR(10) NULL,
  `NOMBRE` VARCHAR(20) NULL,
  `APELLIDO` VARCHAR(20) NULL,
  `CELULAR` INT(9) NULL,
  `EMAIL` VARCHAR(30) NULL,
  `SUELDO_BRUTO` INT(7) NULL,
  `EST_CIVIL` TINYINT(1) NULL,
  `NOM_DEPT` VARCHAR(20) NULL,
  PRIMARY KEY (`CODIGO`));
