/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.RegistroInstrumento;
import Modelo.Guitarra;
import Modelo.Piano;
import javax.swing.JOptionPane;

/**
 *
 * @author Concepción
 */
public class Agregar extends javax.swing.JFrame {

    private static Agregar t = null;

    public static Agregar getAgregar() {
        if (t == null) {
            t = new Agregar();
        }
        return t;
    }

    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
        txtnombre.setEnabled(true);
        txtstock.setEnabled(true);
        rbtguitarra.setEnabled(true);
        rbtpiano.setEnabled(true);
        cbxtipo.setEnabled(false);
        cbxtipo2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbtpiano = new javax.swing.JRadioButton();
        rbtguitarra = new javax.swing.JRadioButton();
        cbxtipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btningresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbxtipo2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jLabel3.setText("Stock");

        jLabel4.setText("AGREGAR INSTRUMENTOS");

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoKeyReleased(evt);
            }
        });

        txtstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstockActionPerformed(evt);
            }
        });
        txtstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstockKeyReleased(evt);
            }
        });

        jLabel5.setText("Instrumento");

        buttonGroup1.add(rbtpiano);
        rbtpiano.setText("Piano");
        rbtpiano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtpianoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtguitarra);
        rbtguitarra.setText("Guitarra");
        rbtguitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtguitarraActionPerformed(evt);
            }
        });

        cbxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Acústica", "Eléctrica", "Eléctroacustica" }));
        cbxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtipoActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo");

        btningresar.setText("INGRESAR");
        btningresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btningresarMouseClicked(evt);
            }
        });

        jLabel7.setText("Tipo");

        cbxtipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Con cola", "Sin cola" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(46, 46, 46)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(btningresar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtguitarra)
                                        .addGap(139, 139, 139)
                                        .addComponent(rbtpiano))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxtipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btningresar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtpiano)
                    .addComponent(rbtguitarra))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cbxtipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtipoActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_cbxtipoActionPerformed
    private void verifica(javax.swing.JTextField t) {
        String teclado = t.getText();
        if (teclado.length() > 0) {
            char tecla = teclado.charAt(teclado.length() - 1);
            teclado = teclado.substring(0, teclado.length() - 1);
            if (!Character.isDigit(tecla)) {
                t.setText(teclado);
            }
        }

    }

    private void vaciar() {
        txtcodigo.setText("");
        txtnombre.setText("");
        txtstock.setText("");
        rbtguitarra.setSelected(false);
        rbtpiano.setSelected(false);
        cbxtipo.setSelectedIndex(0);
        cbxtipo2.setSelectedIndex(0);
        cbxtipo.setEnabled(false);
        cbxtipo2.setEnabled(false);
        buttonGroup1.clearSelection();

    }
    private void rbtguitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtguitarraActionPerformed
        if (rbtguitarra.isSelected()) {
            cbxtipo.setEnabled(true);
            cbxtipo2.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_rbtguitarraActionPerformed

    private void rbtpianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtpianoActionPerformed
        if (rbtpiano.isSelected()) {
            cbxtipo2.setEnabled(true);
            cbxtipo.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtpianoActionPerformed

    private void btningresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btningresarMouseClicked
        RegistroInstrumento in = RegistroInstrumento.getInstancia();
        if (txtcodigo.getText().isEmpty() || txtnombre.getText().isEmpty()
                || txtstock.getText().isEmpty() || (!rbtguitarra.isSelected() && !rbtpiano.isSelected())) {
            JOptionPane.showMessageDialog(this, "Faltan Datos por Ingresar");
            return;
        }
        if (rbtguitarra.isSelected()) {
            if (cbxtipo.getSelectedItem().toString().equals("Seleccione")) {
                JOptionPane.showMessageDialog(this, "Faltan Datos por Ingresar");
                return;
            }
            Guitarra g = new Guitarra(
                    cbxtipo.getSelectedItem().toString(),
                    Integer.parseInt(txtcodigo.getText()),
                    txtnombre.getText(),
                    Integer.parseInt(txtstock.getText())
            );
            if (in.ingresar(g)) {
                JOptionPane.showMessageDialog(this, "Producto Ingresado Correctamente");
                vaciar();
            } else {
                JOptionPane.showMessageDialog(this, "Producto Ya Existe");
            }
        }
        if (rbtpiano.isSelected()) {
            if (cbxtipo2.getSelectedItem().toString().equals("Seleccione")) {
                JOptionPane.showMessageDialog(this, "Faltan Datos por Ingresar");
                return;
            }

            Piano p = new Piano(
                    cbxtipo2.getSelectedItem().toString(),
                    Integer.parseInt(txtcodigo.getText()),
                    txtnombre.getText(),
                    Integer.parseInt(txtstock.getText())
            );
            if (in.ingresar(p)) {
                JOptionPane.showMessageDialog(this, "Producto Ingresado Correctamente");
                vaciar();
            } else {
                JOptionPane.showMessageDialog(this, "Producto Ya Existe");
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btningresarMouseClicked

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        /*if (!txtcodigo.getText().isEmpty()) {
            txtnombre.setEnabled(true);
            txtstock.setEnabled(true);
            rbtguitarra.setEnabled(true);
            rbtpiano.setEnabled(true);
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtcodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyReleased
        verifica(txtcodigo);        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoKeyReleased

    private void txtstockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstockKeyReleased
        verifica(txtstock); 
        if (Integer.parseInt(txtstock.getText()) < 1) {
            JOptionPane.showMessageDialog(this, "Stock debe ser mayor a cero");
            return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtstockKeyReleased

    private void txtstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxtipo;
    private javax.swing.JComboBox<String> cbxtipo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rbtguitarra;
    private javax.swing.JRadioButton rbtpiano;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
