/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Concepción
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Menuarchivo = new javax.swing.JMenu();
        Mtsalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Mtagregar = new javax.swing.JMenuItem();
        Mtlistar = new javax.swing.JMenuItem();
        Mteliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menuarchivo.setText("Archivo");

        Mtsalir.setText("Salir");
        Mtsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MtsalirMouseClicked(evt);
            }
        });
        Mtsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtsalirActionPerformed(evt);
            }
        });
        Menuarchivo.add(Mtsalir);

        jMenuBar1.add(Menuarchivo);

        jMenu2.setText("Procesos");

        Mtagregar.setText("Agregar");
        Mtagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MtagregarMouseClicked(evt);
            }
        });
        Mtagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtagregarActionPerformed(evt);
            }
        });
        jMenu2.add(Mtagregar);

        Mtlistar.setText("Listar");
        Mtlistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MtlistarMouseClicked(evt);
            }
        });
        Mtlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtlistarActionPerformed(evt);
            }
        });
        jMenu2.add(Mtlistar);

        Mteliminar.setText("Eliminar");
        Mteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MteliminarActionPerformed(evt);
            }
        });
        jMenu2.add(Mteliminar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MtsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MtsalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MtsalirMouseClicked

    private void MtagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MtagregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MtagregarMouseClicked

    private void MtlistarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MtlistarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MtlistarMouseClicked

    private void MtsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtsalirActionPerformed
        System.exit(0);   // TODO add your handling code here:
    }//GEN-LAST:event_MtsalirActionPerformed

    private void MtagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtagregarActionPerformed
        Agregar n = Agregar.getAgregar();
        n.setVisible(true);   // doble click en agregar
    }//GEN-LAST:event_MtagregarActionPerformed

    private void MtlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtlistarActionPerformed
        Listar l = Listar.getClase();
        l.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_MtlistarActionPerformed

    private void MteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MteliminarActionPerformed
        Eliminar e = Eliminar.getClase();
        e.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_MteliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menuarchivo;
    private javax.swing.JMenuItem Mtagregar;
    private javax.swing.JMenuItem Mteliminar;
    private javax.swing.JMenuItem Mtlistar;
    private javax.swing.JMenuItem Mtsalir;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
