/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;
import Controlador.Registro;
import Modelo.Chocolate;
import Modelo.Ventas;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Concepción
 */
public class Mantenedor extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form Mantenedor
     */
    public Mantenedor() {
        initComponents();

        /*rbnbitter1.setEnabled(false);
        rbnleche1.setEnabled(false);
        rbnblanco1.setEnabled(false);*/

    }

    public void vaciar() {
        txtcodigo1.setText("");
        txtnombre.setText("");
        txtprecio1.setText("");
        txtcantidad.setText("");
        txtarea1.setText("");
        rbnbitter1.setSelected(false);
        rbnleche1.setSelected(false);
        rbnblanco1.setSelected(false);
        cbxtipo1.setSelectedIndex(0);
        cbxmarca.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        chbazucar1.setSelected(false);
    }

    public void vaciar2() {
        txtcodigo2.setText("");
        txtnombre2.setText("");
        txtprecio2.setText("");
        txtcantidad2.setText("");
        txtarea2.setText("");
        rbnbitter2.setSelected(false);
        rbnleche2.setSelected(false);
        rbnblanco2.setSelected(false);
        cbxtipo2.setSelectedIndex(0);
        cbxmarca2.setSelectedIndex(0);
        buttonGroup2.clearSelection();
        chbazucar.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcodigo1 = new javax.swing.JTextField();
        txtprecio1 = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        cbxtipo1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbxmarca = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        rbnbitter1 = new javax.swing.JRadioButton();
        rbnleche1 = new javax.swing.JRadioButton();
        rbnblanco1 = new javax.swing.JRadioButton();
        chbazucar1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btningresar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcodigo2 = new javax.swing.JTextField();
        txtprecio2 = new javax.swing.JTextField();
        txtnombre2 = new javax.swing.JTextField();
        txtcantidad2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxtipo2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxmarca2 = new javax.swing.JComboBox<>();
        rbnbitter2 = new javax.swing.JRadioButton();
        rbnleche2 = new javax.swing.JRadioButton();
        rbnblanco2 = new javax.swing.JRadioButton();
        chbazucar = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea2 = new javax.swing.JTextArea();
        btnbuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jlcantidad = new javax.swing.JLabel();
        jlprecio = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel9.setText("Código  :");

        jLabel10.setText("Precio   :");

        jLabel11.setText("Tipo       :");

        jLabel12.setText("Nombre    :");

        jLabel13.setText("Cantidad  :");

        txtcodigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigo1KeyReleased(evt);
            }
        });

        txtprecio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprecio1KeyReleased(evt);
            }
        });

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidadKeyReleased(evt);
            }
        });

        cbxtipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Blanco", "Negro", "Con Fruta" }));

        jLabel14.setText("Marca       :");

        cbxmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Nestle", "Costa", "Lafete", "Entrelagos" }));

        jLabel15.setText("Sabor");

        buttonGroup1.add(rbnbitter1);
        rbnbitter1.setText("Bitter");
        rbnbitter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnbitter1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbnleche1);
        rbnleche1.setText("Leche");

        buttonGroup1.add(rbnblanco1);
        rbnblanco1.setText("Blanco");

        chbazucar1.setText("Azucar");
        chbazucar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbazucar1ActionPerformed(evt);
            }
        });

        txtarea1.setColumns(20);
        txtarea1.setRows(5);
        jScrollPane2.setViewportView(txtarea1);

        jLabel16.setText("Descripción     :");

        btningresar.setText("Ingresar");
        btningresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btningresarMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Ingreso Chocolates");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtprecio1)
                                    .addComponent(txtcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxtipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbnblanco1)
                                    .addComponent(rbnleche1)
                                    .addComponent(rbnbitter1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btningresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(chbazucar1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(txtcantidad))
                            .addComponent(cbxmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(txtcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbxtipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbxmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbazucar1)
                            .addComponent(jLabel15))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(rbnbitter1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbnleche1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbnblanco1)
                        .addGap(42, 42, 42)
                        .addComponent(btningresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insertar", jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(45000, 45000));

        jLabel1.setText("Código   :");

        jLabel2.setText("Nombre  :");

        jLabel3.setText("Precio    :");

        jLabel4.setText("Cantidad   :");

        txtprecio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprecio2KeyReleased(evt);
            }
        });

        txtcantidad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidad2KeyReleased(evt);
            }
        });

        jLabel5.setText("Tipo       :");

        cbxtipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Blanco", "Negro", "Con fruta" }));

        jLabel6.setText("Marca       :");

        cbxmarca2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Nestle", "Costa", "Lafete", "Entrelagos" }));

        buttonGroup2.add(rbnbitter2);
        rbnbitter2.setText("Bitter");
        rbnbitter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnbitter2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbnleche2);
        rbnleche2.setText("Leche");

        buttonGroup2.add(rbnblanco2);
        rbnblanco2.setText("Blanco");

        chbazucar.setText("Azucar");

        txtarea2.setColumns(20);
        txtarea2.setRows(5);
        jScrollPane1.setViewportView(txtarea2);

        btnbuscar.setText("Buscar");
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel7.setText("Sabor    :");

        btnactualizar.setText("Actualizar");
        btnactualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnactualizarMouseClicked(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarMouseClicked(evt);
            }
        });

        jLabel8.setText("Descripción   :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbnleche2)
                            .addComponent(rbnblanco2)
                            .addComponent(rbnbitter2))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(32, 32, 32))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtcodigo2)
                                .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxtipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxmarca2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chbazucar)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnactualizar)
                .addGap(54, 54, 54)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxtipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(chbazucar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbxmarca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbnbitter2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(5, 5, 5)
                        .addComponent(rbnleche2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbnblanco2)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Editar", jPanel1);

        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel18.setText("CANTIDAD ");

        jLabel19.setText("PRECIO");

        jlcantidad.setText("jLabel20");

        jlprecio.setText("jLabel21");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("RESUMENES DE VENTA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jlcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlprecio, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addGap(124, 124, 124))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel22)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(557, 557, 557))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        JTabbedPane tabbedPane = (JTabbedPane) evt.getSource();
        int tab = tabbedPane.getSelectedIndex();
        if (tab == 2) {
            Registro g = new Registro();
            Ventas v = g.ventas();
            jlcantidad.setText(String.valueOf(v.getCantidad()));
            jlprecio.setText(String.valueOf(v.getVentas()));
        }
        if (tab == 3) {
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        System.out.println("hola");
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained

    }//GEN-LAST:event_jPanel3FocusGained

    private void btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseClicked
        if (txtcodigo2.getText().isEmpty()
            || txtnombre2.getText().isEmpty()
            || txtprecio2.getText().isEmpty()
            || txtcantidad2.getText().isEmpty()
            || txtarea2.getText().isEmpty()
            || cbxtipo2.getSelectedItem().toString().equals("Seleccione")
            || cbxmarca2.getSelectedItem().toString().equals("Seleccione")
            || (!rbnbitter2.isSelected() && !rbnleche2.isSelected() && !rbnblanco2.isSelected())) {
            JOptionPane.showMessageDialog(this, "Faltan Datos por Ingresar");
            return;
        }
        if (!btneliminar.isEnabled()) {
            return;
        }
        int codigo = Integer.parseInt(txtcodigo2.getText());
        Registro registro = new Registro();
        registro.eliminar(codigo);
        JOptionPane.showMessageDialog(this, "Chocolate Eliminado");
        vaciar2();
    }//GEN-LAST:event_btneliminarMouseClicked

    private void btnactualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnactualizarMouseClicked
        if (txtcodigo2.getText().isEmpty()
            || txtnombre2.getText().isEmpty()
            || txtprecio2.getText().isEmpty()
            || txtcantidad2.getText().isEmpty()
            || txtarea2.getText().isEmpty()
            || cbxtipo2.getSelectedItem().toString().equals("Seleccione")
            || cbxmarca2.getSelectedItem().toString().equals("Seleccione")
            || (!rbnbitter2.isSelected() && !rbnleche2.isSelected() && !rbnblanco2.isSelected())) {
            JOptionPane.showMessageDialog(this, "Faltan Datos por Ingresar");
            return;
        }
        Chocolate c = new Chocolate();
        c.setCodigo(Integer.parseInt(txtcodigo2.getText()));
        c.setNombre(txtnombre2.getText());
        c.setPrecio(Integer.parseInt(txtprecio2.getText()));
        c.setDescripcion(txtarea2.getText());
        c.setCantidad(Integer.parseInt(txtcantidad2.getText()));
        c.setMarca(cbxmarca2.getSelectedItem().toString());

        if (cbxtipo2.getSelectedIndex() == 1) {
            c.setTipo("B");
        }
        if (cbxtipo2.getSelectedIndex() == 2) {
            c.setTipo("N");
        }
        if (cbxtipo2.getSelectedIndex() == 3) {
            c.setTipo("F");
        }
        if (chbazucar.isSelected()) {
            c.setAzucar(true);
        } else {
            c.setAzucar(false);
        }
        if (rbnbitter2.isSelected()) {
            c.setTipo_choc("Chocolate Bitter");
        }
        if (rbnleche2.isSelected()) {
            c.setTipo_choc("Chocolate de Leche");
        }
        if (rbnblanco2.isSelected()) {
            c.setTipo_choc("Chocolate Blanco");
        }
        Registro g = new Registro();
        JOptionPane.showMessageDialog(this, g.actualizar(c));
        vaciar2();// TODO add your handling code here:
    }//GEN-LAST:event_btnactualizarMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
        if (txtcodigo2.getText().isEmpty()) {
            {
                JOptionPane.showMessageDialog(this, "Faltan Datos por Ingresar");
                return;
            }
        }
        int codigo = Integer.parseInt(txtcodigo2.getText());
        Registro r = new Registro();
        Chocolate c = r.buscar(codigo);
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Chocolate No Registrado");
            btnactualizar.setEnabled(false);
            btneliminar.setEnabled(false);
        } else {
            txtnombre2.setText(c.getNombre());
            txtnombre2.setCaretPosition(0);
            txtprecio2.setText("" + c.getPrecio());
            txtcantidad2.setText("" + c.getCantidad());
            txtarea2.setText(c.getDescripcion());
            chbazucar.setSelected(c.isAzucar());
            if (c.getTipo_choc().equals("Chocolate Bitter")) {
                rbnbitter2.setSelected(true);
            }
            if (c.getTipo_choc().equals("Chocolate de Leche")) {
                rbnleche2.setSelected(true);
            }
            if (c.getTipo_choc().equals("Chocolate Blanco")) {
                rbnblanco2.setSelected(true);

            }
            for (int i = 0; i < cbxmarca2.getItemCount(); i++) {
                if (cbxmarca2.getItemAt(i).equals(c.getMarca())) {
                    cbxmarca2.setSelectedIndex(i);
                    break;
                }

            }
            if (c.getTipo().equals("B")) {
                cbxtipo2.setSelectedIndex(1);
            }
            if (c.getTipo().equals("N")) {
                cbxtipo2.setSelectedIndex(2);
            }
            if (c.getTipo().equals("F")) {
                cbxtipo2.setSelectedIndex(3);
            }
            btnactualizar.setEnabled(true);
            btneliminar.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarMouseClicked

    private void rbnbitter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnbitter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnbitter2ActionPerformed

    private void txtcantidad2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidad2KeyReleased
        verifica(txtcantidad2);
        if (Integer.parseInt(txtcantidad2.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Cantidad debe ser mayor o igual a cero");

        }
    }//GEN-LAST:event_txtcantidad2KeyReleased

    private void txtprecio2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio2KeyReleased
        verifica(txtprecio2);
        if (Integer.parseInt(txtprecio2.getText()) < 1) {
            JOptionPane.showMessageDialog(this, "Precio debe ser mayor a cero");

        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtprecio2KeyReleased

    private void btningresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btningresarMouseClicked
        if (txtcodigo1.getText().isEmpty()
            || txtnombre.getText().isEmpty()
            || txtprecio1.getText().isEmpty()
            || txtcantidad.getText().isEmpty()
            || txtarea1.getText().isEmpty()
            || cbxtipo1.getSelectedItem().toString().equals("Seleccione")
            || cbxmarca.getSelectedItem().toString().equals("Seleccione")
            || (!rbnbitter1.isSelected() && !rbnleche1.isSelected() && !rbnblanco1.isSelected())) {
            JOptionPane.showMessageDialog(this, "Faltan Datos por Ingresar");
            return;
        }

        Chocolate c = new Chocolate();
        c.setNombre(txtnombre.getText());
        c.setCodigo(Integer.parseInt(txtcodigo1.getText()));
        c.setPrecio(Integer.parseInt(txtprecio1.getText()));
        c.setDescripcion(txtarea1.getText());
        c.setCantidad(Integer.parseInt(txtcantidad.getText()));
        c.setMarca(cbxmarca.getSelectedItem().toString());

        if (cbxtipo1.getSelectedIndex() == 1) {
            c.setTipo("B");
        }
        if (cbxtipo1.getSelectedIndex() == 2) {
            c.setTipo("N");
        }
        if (cbxtipo1.getSelectedIndex() == 3) {
            c.setTipo("F");
        }
        if (chbazucar1.isSelected()) {
            c.setAzucar(true);
        } else {
            c.setAzucar(false);
        }
        if (rbnbitter1.isSelected()) {
            c.setTipo_choc("Chocolate Bitter");
        }
        if (rbnleche1.isSelected()) {
            c.setTipo_choc("Chocolate de Leche");
        }
        if (rbnblanco1.isSelected()) {
            c.setTipo_choc("Chocolate Blanco");
        }

        Registro g = new Registro();
        JOptionPane.showMessageDialog(this, g.agregar(c));
        vaciar();// TODO add your handling code here:
    }//GEN-LAST:event_btningresarMouseClicked

    private void chbazucar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbazucar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbazucar1ActionPerformed

    private void rbnbitter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnbitter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnbitter1ActionPerformed

    private void txtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyReleased
        verifica(txtcantidad);
        if (Integer.parseInt(txtcantidad.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Cantidad debe ser mayor o igual a cero");

        }
    }//GEN-LAST:event_txtcantidadKeyReleased

    private void txtprecio1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio1KeyReleased
        verifica(txtprecio1);
        if (Integer.parseInt(txtprecio1.getText()) < 1) {
            JOptionPane.showMessageDialog(this, "Precio debe ser mayor a cero");

        }     // TODO add your handling code here:
    }//GEN-LAST:event_txtprecio1KeyReleased

    private void txtcodigo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigo1KeyReleased
        verifica(txtcodigo1);
        String codigo = txtcodigo1.getText();
        if (codigo.length() > 3) {
            JOptionPane.showMessageDialog(this, "Código numérico máx 3 dígitos");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigo1KeyReleased
    private void verifica(javax.swing.JTextField t) {
        String teclado = t.getText();
        if (teclado.length() > 0) {
            char tecla = teclado.charAt(teclado.length() - 1);
            teclado = teclado.substring(0, teclado.length() - 1);
            if (!Character.isDigit(tecla)) {
                t.setText(teclado);
            }
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btningresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxmarca;
    private javax.swing.JComboBox<String> cbxmarca2;
    private javax.swing.JComboBox<String> cbxtipo1;
    private javax.swing.JComboBox<String> cbxtipo2;
    private javax.swing.JCheckBox chbazucar;
    private javax.swing.JCheckBox chbazucar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlcantidad;
    private javax.swing.JLabel jlprecio;
    private javax.swing.JRadioButton rbnbitter1;
    private javax.swing.JRadioButton rbnbitter2;
    private javax.swing.JRadioButton rbnblanco1;
    private javax.swing.JRadioButton rbnblanco2;
    private javax.swing.JRadioButton rbnleche1;
    private javax.swing.JRadioButton rbnleche2;
    private javax.swing.JTextArea txtarea1;
    private javax.swing.JTextArea txtarea2;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcantidad2;
    private javax.swing.JTextField txtcodigo1;
    private javax.swing.JTextField txtcodigo2;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre2;
    private javax.swing.JTextField txtprecio1;
    private javax.swing.JTextField txtprecio2;
    // End of variables declaration//GEN-END:variables
}
