CREATE TABLE `chocolateria`.`chocolate` (
  `CODIGO` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `DESCRIP` VARCHAR(45) NULL,
  `PRECIO` INT NULL,
  `CANTIDAD` INT NULL,
  `TIPO` CHAR(1) NULL,
  `TIPO_C` VARCHAR(45) NULL,
  `MARCA` VARCHAR(45) NULL,
  `AZUCAR` TINYINT(1) NULL,
  PRIMARY KEY (`CODIGO`));
